import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  createDevWitnessKeyPair,
  createWitnessCheckpoint,
  createWitnessCheckpointConsistencyProof
} from "../../packages/research-frontier/src/witnessCheckpoint";

interface CliArgs {
  out?: string;
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = {};
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    const next = argv[index + 1];

    if (arg === "--out") {
      args.out = next;
      index += 1;
    } else if (arg === "--help" || arg === "-h") {
      printUsage();
      process.exit(0);
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }
  return args;
}

function printUsage(): void {
  console.log(`Ghost-Ark research witness bundle generator

Usage:
  npm run research:witness-bundle -- --out examples/research/witness-bundle.local

This generates a local research witness checkpoint bundle:
  - previous-witness-checkpoint.json
  - new-witness-checkpoint.json
  - consistency-proof.json
  - witness-key-manifest.json
  - README.md

Non-claim:
  This is local research evidence only. It is not an independent witness network,
  production transparency log, deployment-safety proof, compliance proof, or AI-safety proof.
`);
}

function required(value: string | undefined, name: string): string {
  if (!value || value.trim().length === 0) {
    throw new Error(`Missing required ${name}`);
  }
  return value;
}

function writeJson(outDir: string, name: string, value: unknown): void {
  writeFileSync(join(outDir, name), `${JSON.stringify(value, null, 2)}\n`, "utf8");
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const outDir = required(args.out, "--out");

  mkdirSync(outDir, { recursive: true });

  const witness = createDevWitnessKeyPair("local-dev-witness-1");

  const previousReceiptPayloads = [
    "tenant=acme-lab;receipt=receipt-a;policy=policy-v1",
    "tenant=acme-lab;receipt=receipt-b;policy=policy-v1"
  ];

  const newReceiptPayloads = [
    ...previousReceiptPayloads,
    "tenant=acme-lab;receipt=receipt-c;policy=policy-v1",
    "tenant=acme-lab;receipt=receipt-d;policy=policy-v1"
  ];

  const previousCheckpoint = createWitnessCheckpoint({
    logId: "ghost-ark-local-research-log",
    receiptPayloads: previousReceiptPayloads,
    integratedTime: "2026-07-08T12:00:00.000Z",
    witness
  });

  const newCheckpoint = createWitnessCheckpoint({
    logId: "ghost-ark-local-research-log",
    receiptPayloads: newReceiptPayloads,
    integratedTime: "2026-07-08T12:01:00.000Z",
    witness
  });

  const proof = createWitnessCheckpointConsistencyProof({
    previousCheckpoint,
    newCheckpoint,
    receiptPayloads: newReceiptPayloads
  });

  const manifest = {
    schema_version: "ghostark.research.witness_key_manifest.v1",
    generated_at: "2026-07-08T12:00:30.000Z",
    witnesses: [
      {
        witness_id: witness.witnessId,
        signature_algorithm: "ecdsa-p256-sha256",
        public_key_pem: witness.publicKeyPem,
        valid_from: "2026-07-08T00:00:00.000Z",
        status: "ACTIVE"
      }
    ]
  };

  writeJson(outDir, "previous-witness-checkpoint.json", previousCheckpoint);
  writeJson(outDir, "new-witness-checkpoint.json", newCheckpoint);
  writeJson(outDir, "consistency-proof.json", proof);
  writeJson(outDir, "witness-key-manifest.json", manifest);

  writeFileSync(
    join(outDir, "README.md"),
    `# Ghost-Ark Local Research Witness Bundle

This directory was generated by:

\`\`\`bash
npm run research:witness-bundle -- --out ${outDir}
\`\`\`

Verify it with:

\`\`\`bash
node tools/ghost-verify.mjs \\
  --witness-checkpoint-consistency-proof ${outDir}/consistency-proof.json \\
  --previous-witness-checkpoint ${outDir}/previous-witness-checkpoint.json \\
  --new-witness-checkpoint ${outDir}/new-witness-checkpoint.json \\
  --witness-key-manifest ${outDir}/witness-key-manifest.json
\`\`\`

Expected result:

\`\`\`text
VERDICT: PASS
\`\`\`

## What This Demonstrates

This demonstrates local research witness checkpoint consistency verification under Ghost-Ark verifier rules.

## Non-Claims

This does not prove AI safety, evidence truth, production readiness, compliance, deployment safety, independent witness publication, or decentralized transparency.

This is a local reproducibility artifact, not a production transparency log.
`,
    "utf8"
  );

  console.log(`Wrote local research witness bundle to ${outDir}`);
  console.log("");
  console.log("Verify with:");
  console.log(`node tools/ghost-verify.mjs \\`);
  console.log(`  --witness-checkpoint-consistency-proof ${outDir}/consistency-proof.json \\`);
  console.log(`  --previous-witness-checkpoint ${outDir}/previous-witness-checkpoint.json \\`);
  console.log(`  --new-witness-checkpoint ${outDir}/new-witness-checkpoint.json \\`);
  console.log(`  --witness-key-manifest ${outDir}/witness-key-manifest.json`);
}

if (require.main === module) {
  try {
    main();
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exitCode = 1;
  }
}
