//! Ghost-Ark DAB Tier-0
//!
//! Declarative Action Binding
//!
//! Cryptographic Receipt Layer
//!
//! Responsibilities:
//!
//! 1. Define the immutable execution receipt format.
//! 2. Bind declaration commitment (C_I).
//! 3. Bind execution commitment (C_E).
//! 4. Bind nonce / replay identity.
//! 5. Bind policy version.
//! 6. Bind gateway identity.
//! 7. Provide deterministic signing material.
//!
//!
//! Security model:
//!
//! Agent runtime:
//!     creates C_I
//!
//! Gateway:
//!     observes bytes
//!     creates C_E
//!     signs receipt
//!
//! Verifier:
//!     independently verifies receipt
//!
//!
//! This module does NOT prove:
//!
//! - human intent
//! - semantic correctness
//! - AI alignment
//!
//! It proves:
//!
//! "The gateway executed the exact bytes
//!  that were declared."



use serde::{
    Deserialize,
    Serialize,
};

use sha2::{
    Digest,
    Sha256,
};




/// Protocol identifier.
///
/// Any incompatible change
/// requires a new protocol version.
pub const RECEIPT_PROTOCOL_VERSION:
    &str =
    "DAB-TIER0-RECEIPT-V1";




/// Gateway identity.
///
/// Production deployments should replace this with:
///
/// - TPM identity
/// - Nitro Enclave identity
/// - KMS key ARN
/// - HSM certificate
///
pub const GATEWAY_ID:
    &str =
    "ghost-ark-dab-gateway-tier0";





/// Receipt status.
///
/// The verifier treats anything
/// except CERTIFIED as failure.
#[derive(
    Debug,
    Serialize,
    Deserialize,
    Clone,
    PartialEq
)]
pub enum ReceiptStatus {


    /// Execution occurred.
    CERTIFIED,


    /// C_I != C_E.
    MUTATION_DETECTED_HALT,


    /// Nonce already consumed.
    REPLAY_REJECTED,


    /// Schema or validation failure.
    INVALID,



    /// External execution failed.
    EXECUTION_FAILED,

}





/// Canonical DAB receipt.
///
/// This object is the artifact
/// persisted for later verification.
#[derive(
    Debug,
    Serialize,
    Deserialize,
    Clone
)]
pub struct DABReceipt {



    /// Protocol version.
    pub protocol:
        String,



    /// Gateway identity.
    pub gateway_id:
        String,



    /// Execution result.
    pub status:
        ReceiptStatus,



    /// Declared Action Commitment.
    ///
    /// Generated by DANF.
    pub c_i:
        String,



    /// Execution Commitment.
    ///
    /// Independently computed
    /// by gateway.
    pub c_e:
        String,



    /// Replay protection nonce.
    pub nonce:
        String,



    /// Transaction identifier.
    ///
    /// Protects against concurrency swaps.
    pub transaction_id:
        String,



    /// Policy binding.
    ///
    /// Hash of:
    ///
    /// policy_version
    /// policy_rules
    /// evaluator_version
    ///
    pub policy_digest:
        String,



    /// Unix timestamp.
    pub timestamp:
        String,



    /// Cryptographic signature.
    pub signature:
        String,

}






impl DABReceipt {



    /// Create certified receipt.
    pub fn certified(
        c_i:String,
        c_e:String,
        nonce:String,
        transaction_id:String,
        policy_digest:String,
        timestamp:String,
        signature:String,
    )
    -> Self {



        Self {

            protocol:
                RECEIPT_PROTOCOL_VERSION
                .to_string(),


            gateway_id:
                GATEWAY_ID
                .to_string(),


            status:
                ReceiptStatus::CERTIFIED,


            c_i,


            c_e,


            nonce,


            transaction_id,


            policy_digest,


            timestamp,


            signature,

        }

    }







    /// Create rejection receipt.
    ///
    /// Rejections are still signed
    /// in production systems.
    pub fn rejected(
        status:ReceiptStatus,
        c_i:String,
        c_e:String,
        nonce:String,
        transaction_id:String,
    )
    -> Self {



        Self {


            protocol:
                RECEIPT_PROTOCOL_VERSION
                .to_string(),


            gateway_id:
                GATEWAY_ID
                .to_string(),


            status,


            c_i,


            c_e,


            nonce,


            transaction_id,


            policy_digest:
                "NULL".into(),


            timestamp:
                current_timestamp(),


            signature:
                "".into(),

        }

    }







    /// Produce canonical signing payload.
    ///
    /// IMPORTANT:
    ///
    /// Never sign JSON directly.
    ///
    /// JSON formatting can vary.
    ///
    /// Sign deterministic fields.
    pub fn signing_material(
        &self
    )
    -> String {


        format!(
            "{}|{}|{}|{}|{}|{}|{}|{}|{}",
            self.protocol,
            self.gateway_id,
            status_string(&self.status),
            self.c_i,
            self.c_e,
            self.nonce,
            self.transaction_id,
            self.policy_digest,
            self.timestamp
        )

    }







    /// Hash signing payload.
    ///
    /// Useful for:
    ///
    /// - audit logs
    /// - transparency ledger
    /// - benchmark comparison
    pub fn signing_digest(
        &self
    )
    -> String {


        let mut hasher =
            Sha256::new();


        hasher.update(
            self.signing_material()
                .as_bytes()
        );


        format!(
            "sha256:{:x}",
            hasher.finalize()
        )

    }






    /// Security invariant:
    ///
    /// Certified receipts require:
    ///
    /// C_I == C_E
    pub fn execution_consistent(
        &self
    )
    -> bool {


        self.status
            ==
            ReceiptStatus::CERTIFIED

        &&
        
        self.c_i
            ==
            self.c_e

    }

}








/// Convert enum to deterministic string.
fn status_string(
    status:&ReceiptStatus
)
-> &'static str {


    match status {


        ReceiptStatus::CERTIFIED =>
            "CERTIFIED",


        ReceiptStatus::MUTATION_DETECTED_HALT =>
            "MUTATION_DETECTED_HALT",


        ReceiptStatus::REPLAY_REJECTED =>
            "REPLAY_REJECTED",


        ReceiptStatus::INVALID =>
            "INVALID",


        ReceiptStatus::EXECUTION_FAILED =>
            "EXECUTION_FAILED",

    }

}









/// Placeholder timestamp.
///
/// Replace with trusted clock source
/// for high assurance deployments.
fn current_timestamp()
-> String {


    use std::time::{
        SystemTime,
        UNIX_EPOCH,
    };


    SystemTime::now()
        .duration_since(
            UNIX_EPOCH
        )
        .unwrap()
        .as_secs()
        .to_string()

}









/// Receipt signer abstraction.
///
/// Future implementations:
///
/// - AWS KMS Sign
/// - Nitro Enclave key
/// - TPM-backed key
/// - HSM
///
pub trait ReceiptSigner {


    fn sign(
        &self,
        message:&str
    )
    -> Result<String,String>;

}









/// Development signer.
///
/// NOT cryptographic security.
///
/// Only for local artifact reproduction.
///
/// Replace before publication claims.
pub struct DevelopmentSigner;

impl ReceiptSigner for DevelopmentSigner {


    fn sign(
        &self,
        message:&str
    )
    -> Result<String,String>{


        Ok(
            format!(
                "DEV:{}",
                sha256_string(message)
            )
        )

    }

}







fn sha256_string(
    value:&str
)
-> String {


    let mut hasher =
        Sha256::new();


    hasher.update(
        value.as_bytes()
    );


    format!(
        "{:x}",
        hasher.finalize()
    )

}